# Generated by Django 4.2.2 on 2023-10-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Linke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(db_index=True)),
                ('employee_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('count_of_clients', models.IntegerField(default=0)),
                ('number_of_url', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
